from enum import Enum

class UserRole(Enum):
    ESG_ADMIN = "ESG_ADMIN"
    ESG_APPROVER = "ESG_APPROVER"
    ESG_CONTRIBUTOR = "ESG_CONTRIBUTOR"
    ESG_READONLY = "ESG_READONLY"
    ESG_EXTERNAL_CONTRIBUTOR = "ESG_EXTERNAL_CONTRIBUTOR"